// <auto-generated />
using System;
using Manufacturing_Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manufacturing_Core.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260512101111_five")]
    partial class five
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Manufacturing_Core.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MAccountType", b =>
                {
                    b.Property<int>("PkAccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkAccountTypeId"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("Varchar(150)");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FkBankId")
                        .HasColumnType("int");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkAccountTypeId");

                    b.ToTable("MAccountTypes");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MAddress", b =>
                {
                    b.Property<int>("PkAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkAddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CurrentAddress")
                        .HasColumnType("bit");

                    b.Property<string>("CurrentAddressLine1")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("CurrentAddressLine2")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("EMailId")
                        .HasColumnType("Varchar(100)");

                    b.Property<int>("FKLedgerNo")
                        .HasColumnType("int");

                    b.Property<int>("FkSupId")
                        .HasColumnType("int");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<bool?>("OfficeAddress")
                        .HasColumnType("bit");

                    b.Property<string>("OfficeAddressLine1")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("OfficeAddressLine2")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("OfficeCity")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("OfficeCountry")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("OfficePhNo")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("OfficePin")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("OfficeState")
                        .HasColumnType("Varchar(50)");

                    b.Property<bool>("PermAddress")
                        .HasColumnType("bit");

                    b.Property<string>("PermAddressLine1")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("PermAddressLine2")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("PermCity")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("PermCountry")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("PermPhNo")
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("PermPin")
                        .HasColumnType("Varchar(6)");

                    b.Property<string>("PermState")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("PhNo")
                        .IsRequired()
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("Varchar(6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkAddressId");

                    b.ToTable("MAddresses");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MAuthors", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("Varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MBank", b =>
                {
                    b.Property<int>("PkBankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkBankId"));

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("Varchar(25)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkAccountTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FkBankId")
                        .HasColumnType("int");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("Varchar(25)");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("MICRCode")
                        .IsRequired()
                        .HasColumnType("Varchar(25)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkBankId");

                    b.HasIndex("FkAccountTypeId");

                    b.ToTable("MBanks");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MBooks", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.ToTable("MBooks");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MCategory", b =>
                {
                    b.Property<int>("PkCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkCatId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("Varchar(1000)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkTypeId")
                        .HasColumnType("int");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkCatId");

                    b.HasIndex("FkTypeId");

                    b.ToTable("MCategory");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MItem", b =>
                {
                    b.Property<int>("PkItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkItemId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("Varchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkCatId")
                        .HasColumnType("int");

                    b.Property<string>("HSNCODE")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("Varchar(500)");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<int>("ItemQty")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("ItemUnit")
                        .HasColumnType("float");

                    b.Property<int?>("MTypePkTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SACODE")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkItemId");

                    b.HasIndex("FkCatId");

                    b.HasIndex("MTypePkTypeId");

                    b.ToTable("MItems");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MLedger", b =>
                {
                    b.Property<int>("PKLedgerNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKLedgerNo"));

                    b.Property<string>("BSTNo")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("CSTNo")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("Varchar(500)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExciseRegestrationNo")
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("FaxNo")
                        .HasColumnType("Varchar(20)");

                    b.Property<int>("FkBankId")
                        .HasColumnType("int");

                    b.Property<string>("GSTINNo")
                        .IsRequired()
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("IncomeTaxNo")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsServiceTaxApply")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("LedgerName")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("LedgerUserNo")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("OpeningBalance")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("PANNo")
                        .HasMaxLength(10)
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("SaleTaxNo")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("ServiceTaxRegNo")
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("UINNo")
                        .IsRequired()
                        .HasColumnType("Varchar(15)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VATNo")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.HasKey("PKLedgerNo");

                    b.HasIndex("FkBankId");

                    b.ToTable("MLedgers");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("MLocations");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MMetarial", b =>
                {
                    b.Property<int>("PkMatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkMatId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HSNCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("MatCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MatDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("MatQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MatRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MatUnit")
                        .HasColumnType("int");

                    b.Property<string>("SACode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkMatId");

                    b.ToTable("MMetarials");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MProduct", b =>
                {
                    b.Property<int>("PkProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkProdId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("ProdCode")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("ProdDescription")
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("ProdImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ProdQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkProdId");

                    b.ToTable("MProducts");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MPurchaseOrder", b =>
                {
                    b.Property<int>("PO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PO_ID"));

                    b.Property<string>("Approved_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Approved_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<DateTime?>("Delivery_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GSTPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool?>("IsSyncronized")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PO_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PO_Number")
                        .IsRequired()
                        .HasColumnType("Varchar(13)");

                    b.Property<string>("PO_Status")
                        .IsRequired()
                        .HasColumnType("Varchar(25)");

                    b.Property<string>("Payment_Terms")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("Varchar(500)");

                    b.Property<int>("Supplier_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PO_ID");

                    b.ToTable("MPurchaseOrders");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MPurchaseOrderDetails", b =>
                {
                    b.Property<int>("PODetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PODetailID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PO_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseOrderPO_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UOM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PODetailID");

                    b.HasIndex("PurchaseOrderPO_ID");

                    b.ToTable("MPurchaseOrderDetails");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MSubcategory", b =>
                {
                    b.Property<int>("PkSubCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkSubCatId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkCatId")
                        .HasColumnType("int");

                    b.Property<int>("FkTypeId")
                        .HasColumnType("int");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("SubCategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkSubCatId");

                    b.HasIndex("FkCatId");

                    b.HasIndex("FkTypeId");

                    b.ToTable("MSubcategory");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MSupplier", b =>
                {
                    b.Property<int>("PkSupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkSupId"));

                    b.Property<string>("CSTNo")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GSTIn")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LicenceId")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("Varchar(25)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TINno")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VATNo")
                        .HasColumnType("varchar(25)");

                    b.HasKey("PkSupId");

                    b.ToTable("MSuppliers");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MType", b =>
                {
                    b.Property<int>("PkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkTypeId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("Varchar(150)");

                    b.Property<bool?>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("Varchar(150)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("TypeDescription")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("Varchar(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkTypeId");

                    b.ToTable("MTypes");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MWarehouses", b =>
                {
                    b.Property<int>("PkWarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkWarehouseId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MWarehousesPkWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkWarehouseId");

                    b.HasIndex("MWarehousesPkWarehouseId");

                    b.ToTable("MWarehouses");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrCurrentStock", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialPkMatId")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("WarehousePkWarehouseId")
                        .HasColumnType("int");

                    b.HasKey("MaterialId", "WarehouseId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MaterialPkMatId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WarehousePkWarehouseId");

                    b.ToTable("TrCurrentStocks");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrInventory", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransId"));

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WarehousePkWarehouseId")
                        .HasColumnType("int");

                    b.HasKey("MaterialId", "WarehouseId", "TransactionDate");

                    b.HasIndex("LocationId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WarehousePkWarehouseId");

                    b.ToTable("TrInventories");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrInventoryTransaction", b =>
                {
                    b.Property<int>("PkInTransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkInTransId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkMatId")
                        .HasColumnType("int");

                    b.Property<int>("FkWarehouseId")
                        .HasColumnType("int");

                    b.Property<int?>("IsCreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<int?>("IsUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("MatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Warehouse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkInTransId");

                    b.HasIndex("FkMatId");

                    b.ToTable("TrInventoryTransaction");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrPORequirementCollection", b =>
                {
                    b.Property<int>("PkRequirementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkRequirementID"));

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BOMNumber")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("MatDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchaseQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RequiredQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequirementNumber")
                        .IsRequired()
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("RequirementSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequirementStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockAvailableQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasColumnType("Varchar(15)");

                    b.HasKey("PkRequirementID");

                    b.ToTable("TrPORequirementCollections");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrRequirementCollection", b =>
                {
                    b.Property<int>("RequirementCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementCollectionId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Designation")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("ExperienceRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(Max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfEmployeesRequired")
                        .HasColumnType("int");

                    b.Property<string>("SelectionCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillsRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RequirementCollectionId");

                    b.ToTable("TrRequirementCollections");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrStockGoodsORScrap", b =>
                {
                    b.Property<int>("PkStGoodScrapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkStGoodScrapId"));

                    b.Property<DateTime>("CheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkMatId")
                        .HasColumnType("int");

                    b.Property<int>("FkWarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("FlagGoodsOrScrap")
                        .HasColumnType("int");

                    b.Property<string>("IsCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("bit");

                    b.Property<string>("IsUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitMeasurement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkStGoodScrapId");

                    b.ToTable("TrStockGoodsORScrap");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrStockLedger", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("StockLedgerId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int?>("WarehousePkWarehouseId")
                        .HasColumnType("int");

                    b.HasKey("MaterialId", "WarehouseId", "TransactionDate");

                    b.HasIndex("LocationId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WarehousePkWarehouseId");

                    b.ToTable("TrStockLedgers");
                });

            modelBuilder.Entity("Manufacturing_Core.ViewModels.TrInventoryViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrInventoryViewModels");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MBank", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MAccountType", "MAccountTypes")
                        .WithMany("MBanks")
                        .HasForeignKey("FkAccountTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MAccountTypes");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MBooks", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MAuthors", "MAuthor")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MAuthor");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MCategory", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MType", "MType")
                        .WithMany("Category")
                        .HasForeignKey("FkTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MType");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MItem", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MCategory", "mCategory")
                        .WithMany()
                        .HasForeignKey("FkCatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MType", null)
                        .WithMany("Item")
                        .HasForeignKey("MTypePkTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("mCategory");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MLedger", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MBank", "MBanks")
                        .WithMany()
                        .HasForeignKey("FkBankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MBanks");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MLocation", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MWarehouses", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MPurchaseOrderDetails", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MPurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderPO_ID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MSubcategory", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MCategory", "MCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("FkCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MType", "MType")
                        .WithMany("Subcategories")
                        .HasForeignKey("FkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MCategory");

                    b.Navigation("MType");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MWarehouses", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MWarehouses", null)
                        .WithMany("Warehouse")
                        .HasForeignKey("MWarehousesPkWarehouseId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrCurrentStock", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MLocation", "Location")
                        .WithMany("CurrentStocks")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MMetarial", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MMetarial", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialPkMatId");

                    b.HasOne("Manufacturing_Core.Entity.MWarehouses", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MWarehouses", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehousePkWarehouseId");

                    b.Navigation("Location");

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrInventory", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MLocation", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MMetarial", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MWarehouses", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MWarehouses", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehousePkWarehouseId");

                    b.Navigation("Location");

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrInventoryTransaction", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MMetarial", "MMetarial")
                        .WithMany()
                        .HasForeignKey("FkMatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MMetarial");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.TrStockLedger", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.MLocation", "Location")
                        .WithMany("StockLedgers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MMetarial", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MWarehouses", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.MWarehouses", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehousePkWarehouseId");

                    b.Navigation("Location");

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manufacturing_Core.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Manufacturing_Core.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MAccountType", b =>
                {
                    b.Navigation("MBanks");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MCategory", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MLocation", b =>
                {
                    b.Navigation("CurrentStocks");

                    b.Navigation("Inventories");

                    b.Navigation("StockLedgers");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MPurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MType", b =>
                {
                    b.Navigation("Category");

                    b.Navigation("Item");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("Manufacturing_Core.Entity.MWarehouses", b =>
                {
                    b.Navigation("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
